config/routes.rb
NativePortal::Application.routes.draw do

  
  match 'login', :controller => 'users', :action => 'new'
  match 'logout', :controller => 'users', :action => 'destroy'
  
  resources :main, :news, :gaming, :section, :post, :entries, :users
  match "/main" => "main#index"
  
  root :to => 'main#index'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :section
  attr_accessible :content, :title, :url, :section_id, :author
  
    def getFirst(n)
    words = content.split(' ')
    if(words.length > n)
      words[0...n].join(' ').html_safe
    else
      content.html_safe
    end
  end
  
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title, :url
  
  def getFirst(n)
    words = content.split(' ')
    if(words.length > n)
      words[0...n].join(' ').html_safe
    else
      content.html_safe
    end
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #session :session_key => '_sora_havok_session'
  
  helper_method :admin?, :user?, :get_user
  
  def authorize_user
    unless user?
      flash[:error] = "Unauthorized Access"
    end
    user?
  end
  
  def authorize_admin
    unless admin?
      flash[:error] = "Unauthorized Access"
      #"#{User.find_by_name("admin").id} vs #{session[:uid].to_i} #{User.find_by_name("admin").id == session[:uid].to_i}"
    end
    admin?
  end
  
  
  def admin?
    session[:uid].to_i == User.find_by_name("admin").id
  end
  
  def user?
    !session[:uid].nil?
  end
  
  def get_user
    User.find(session[:uid])
  end
  
  
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])
    @title = "#{@entry.section.title} - #{@entry.title}"
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
    unless authorize_user
      redirect_to @entry and return
    end
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])
  
    unless authorize_user
      redirect_to @entry and return
    end
      
    respond_to do |format|
      if @entry.update_attributes(params[:entry])
       format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    session[:uid] = params[:uid]
    @entry = Entry.find(params[:id])
    unless authorize_admin
      redirect_to @entry and return
    end
    
    section = @entry.section
    flash[:notice] = "Deleted Entry: #{@entry.title}"
    @entry.destroy
    
    respond_to do |format|
      format.html { redirect_to :controller=>'section', :action => 'show', :id => section}
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index 
	  @title = 'Home'
	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])
    
    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/section_controller.rb
class SectionController < ApplicationController
  def show
    @section = Section.find(params[:id])
    @title = @section.title
    @entries = Entry.find_all_by_section_id(@section)   
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    user = User.find_by_name(params[:user][:name])
    
    if !user.nil? && user.password == params[:user][:password]
      session[:uid] = user.id      
      flash[:notice] = "Successfully logged in as #{user.name}"
      redirect_to '/'
    else
      flash[:error] = "Incorrect Username or Password"
      redirect_to login_path
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    reset_session
    flash[:notice] = "Successfully logged out"
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/section_helper.rb
module SectionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_article.html.erb
<article>
  <h3>
    <% if(abbreviate) %>
      <%= link_to entry.title, entry %>
    <% else %>
      <%= entry.title %>
    <% end %>
  </h3>
  <h5>
    By <%=entry.author %>
  </h5>
 
  
  <p>
    <% words = entry.content.split(' ')
    if(abbreviate && words.length>100) %>
      <%= entry.getFirst(100) %>  ... 
      <%= link_to '[more]', entry %>
    <% else %>
      <%= entry.content.html_safe %>
    <% end %>
  </p>
  
  <% if(!entry.url.nil? && entry.url.length > 0) %>
    Source: <%= link_to entry.url, entry.url %>
    <br />
  <% end %>
  
  <br />
  <% if user? %>
  <div class="text-right">
    <%= link_to 'Edit', edit_entry_path(entry) %>
    <% if admin? %>
      <span>&nbsp;&nbsp;</span>
      <%= link_to 'Delete', entry_path(entry, uid: session[:uid]), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
  <% end %>
</article>
<hr />

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row collapse">
  
    <div class="two columns">
      <span class="prefix">
        <%= f.label "Choose a Section:" %>
      </span>
    </div>
    <div class="ten mobile-three columns" style="padding-bottom:20px;">
      <% Section.all.each do |sec| %>
        <div class="left" style="padding-right:30px; padding-top:5px">
        <%= f.label "#{:section_id}_#{sec.id}", sec.title %>
        <%= f.radio_button :section_id, sec.id, checked: @entry.nil? || @entry.section == sec %>
        </div>
      <% end %>
    </div>
  
  
    
    <div class="small-3 large-2 columns">
      <span class="prefix">
        <%= f.label :title %>
      </span>
    </div>
    <div class="small-9 large-10 columns">
      <%= f.text_field :title %>
    </div>
  
  
    <div class="small-3 large-2 columns">
      <span class="prefix">
       <%= f.label :author %>
      </span>
    </div>
    <div class="small-9 large-10 columns">
      <%= f.text_field :author %>
    </div>
  
  
    <div class="small-3 large-2 columns">
      <span class="prefix">
       <%= f.label :url %>
      </span>
    </div>
    <div class="small-9 large-10 columns">
      <%= f.text_field :url %>
    </div>
  
  
    <span class="prefix">
      <%= label :content, "Content"%>
    </span>
    <br />
    <%= f.text_area :content, :class => "tinymce", :rows => 140, :cols => 120 %>
    <br />

  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', @entry.section %>

app/views/entries/index.html.erb
<h1 class="text-center">All Entries</h1>

<% @entries.each do |entry| %>
  <%= render 'article', entry: entry, abbreviate: true %>
<% end %>

<br />
<% if user? %>
  <%= link_to 'New Entry', new_entry_path %>
<% end %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<% if(true) %>
  <%= render 'article', entry: @entry, abbreviate: false %>
<% else %>
  <p>
    <b>Section:</b>
    <%= @entry.section.title %>
  </p>

  <p>
    <b>Title:</b>
    <%= @entry.title %>
  </p>

  <p>
    <b>Url:</b>
    <%= @entry.url %>
  </p>

  <p>
    <b>Content:</b>
    <%= @entry.content %>
  </p>
  <%= link_to 'Edit', edit_entry_path(@entry) %> |
<% end %>

<%= link_to 'Back', @entry.section %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />
  <% if(@title.nil?) %>  
    <title>Native Portal</title>
  <% else %>
    <title>Native Portal | <%=@title%></title>
  <% end %>
  <%= stylesheet_link_tag "application", :media => "all"%>
</head>
<body>

  <!-- Nav Bar -->

  <div class="row">
    <div class="large-12 columns">
      <%= link_to image_tag("banner.png", { :class=>"left"}), :main_index %>
      <div class="nav-bar left clear">
        <ul class="button-group">
          <li><%=link_to "Home", :main_index, { :class=>"button"}%></li>
          <% Section.all.each do |sec| %>
            <li><%= link_to sec.title, sec, { :class=>"button"}%></li>
          <% end %>
        </ul>
      </div>
    <span class="right">
      <% if user?%>
        <%=link_to "Logout", :logout, { :class=>"small success button"}%>
        <br />
        Hi <%=get_user.name %>!
      <% else %>
        <%=link_to "Login", :login, { :class=>"small success button"}%>
      <% end %>
     </span>
    <hr />
    </div>
     
  </div>

  <!-- End Nav -->


  <!-- Main Page Content and Sidebar -->

  <div class="row">

    <!-- Main Blog Content -->
    <div class="large-9 columns" role="content">
      
      <% if flash[:error] %>
        <div class="error alert-box alert text-center"><%=h flash[:error] %></div>
      <% end %>
      <% if flash[:notice] %>
        <div class="notice alert-box text-center success"><%=h flash[:notice] %></div>
      <% end %>
      
      <%= yield %>
    </div>

    <!-- End Main Content -->


    <!-- Sidebar -->

    <aside class="large-3 columns">

      <h5>Categories</h5>
      <ul class="side-nav">
        <% Section.all.each do |sec| %>
          <li><%= link_to sec.title, sec %></li>
        <% end %>
      </ul>

      <div class="panel">
        <h5>Featured:</h5>
        <% feat = Entry.order("updated_at desc").first %>
        <p>
          <b>
            <%=link_to feat.title, feat%>
          </b>
          <%=feat.getFirst(50) %>
          <br />
          <%=link_to 'Read More', feat%>
        </p>
      </div>

    </aside>

    <!-- End Sidebar -->
  </div>

  <!-- End Main Content and Sidebar -->


  <!-- Footer -->

  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>&copy; Copyright Sora Havok</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- End Footer -->
</body>
<%= javascript_include_tag :application %>
<%= tinymce %>
</html>

app/views/main/index.html.erb
<h3>
  California Tribal Gambling: Tribal Perspective
</h3>
<p>
In California, Indian tribes have survived an onslaught of foreign immigrants into North America since the late 15th century. It is remarkable that independent tribes still exist despite the unthinkable loss of life that took place through disease, war, and other factors.
</p>
<p>
Even today, there are economic and political issues that threaten native tribes and their development today. Ugly tropes about Indians still exist in today’s society; some are new developments but many are simply a continuation from centuries earlier. Many tribes have received funding and reparations from the US Federal government for past indiscretions committed by settlers and the government itself. Many people believe that since the Federal government has offered aid and given out settlements to tribes that Indians in general have become rich off of taxpayer dollars. This ‘rich Indian trope’ comes into play most markedly when tribal gaming comes into the public view. The reality is that most tribes are not economically well off, despite how they are perceived, and it is much easier to start a casino when Federal funding and taxes on the casino winnings are relaxed.
</p>
<p>
Many in California, and other states around the nation, find this to be unfair and see it as special treatment. The fact is, tribes are not attempting to buy into some get rich scheme, but rather provide a source of monetary income for their tribal members. Unfortunately, this is only a brief look at one of many tropes that exist around Indian gaming. Casinos are one way that tribes are attempting to better themselves and exercise their sovereignty.
</p>
<p>
Even with all of these obstacles, several tribes in California have successfully opened casinos and become economically viable. These casinos have brought money into the tribe, provided jobs for tribal members, and opened the door for these tribes and their members to control their own destiny.
</p>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <br />
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <br />
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :class => "tinymce", :rows => 140, :cols => 120 %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/section/show.html.erb
<h2 class="text-center"><%= @section.title %></h2>

<% @entries.each do |entry| %>
  <%= render 'entries/article', entry: entry, abbreviate: true %>
<% end %>

<br />

<%= link_to "New #{@section.title}", new_entry_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit 'Login' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Login</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>